version: "3.9"

services:
  web:
    image: golang:latest
    container_name: my-golang-app
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    command: go run main.go
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  db:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
